### PR TITLE
Feat add validation to automatch response form

### PR DESCRIPTION
**Pull request by nazneen1022**
## User responses to Automatch results - Validation

To enable the submit button on the automatch results form, the following two criteria are validated.

1. a user has to provide responses to all the automatch results either by clicking 'It's the same' or 'It's different' buttons with comments specifying how his/her idea is different.
2. the user should also answer the additional questions on the form.

### CODE REVIEW

**Review by mr-robak — APPROVED** [review]
Looks amazing!!!

**Review by DarianRushworth — APPROVED** [review]
Very cool idea on the validation, super out of the box and smart. Great Work

**Comment by nazneen1022** [comment]
> Very cool idea on the validation, super out of the box and smart. Great Work

Thank you!! :)

**Comment by nazneen1022** [comment]
> Looks amazing!!!

Thank you for the quick review and testing!! 👍

**Review by dashakrolik — APPROVED** [review]

**Pull request merged**
