### PR TITLE
show valid message if idea can't be processed by the ipscreener

### PR DESCRIPTION
**Pull request by nazneen1022**
## Error handling when ipscreener cannot process the idea text.
**Issue:**
When the ipscreener cannot process the idea text an error ("unprocessible entity") is thrown in the catch block but the error data is not captured or handled to notify the user about this while viewing the patent check results. In this scenario, currently the user can only see an infinite loading screen without any proper message.

**Solution:**
As a solution to handle this "unprocessible entity" error, we have to

- add additional columns to the auto_matches table to track the status of ipscreener POST request.
- save the response (success/failure) with status code and message of ipscreener POST request in the additional columns created.
- check the value in the status column of auto_matches table and based on the status code, either display the patent results or proper error message to the user to notify what is happening.

### CODE REVIEW

**Review by mr-robak — APPROVED** [review]
I think this varialble is redundant
 const [errorFound, setErrorFound] = useState(false);

should be possible to only check if there is errorMessage ?

**Review by DarianRushworth — APPROVED** [review]
This took along time and a lot of brain cells, Well Done Nazneen!!  I think Marcin might be correct maybe just have another look over it.

**Comment by nazneen1022** [comment]
> I think this varialble is redundant
> const [errorFound, setErrorFound] = useState(false);
> 
> should be possible to only check if there is errorMessage ?

Thank you for your review and appreciate your observation. Yes, I agree with you, and my intention to have this variable with error message value is to possibly use it in the future for errors (other than 422) if it makes sense.

**Comment by mr-robak** [comment]
> > I think this varialble is redundant
> > const [errorFound, setErrorFound] = useState(false);
> > should be possible to only check if there is errorMessage ?
> 
> Thank you for your review and appreciate your observation. Yes, I agree with you, and my intention to have this variable with error message value is to possibly use it in the future for errors (other than 422) if it makes sense.

Make sense, good job Nazneen!

**Pull request merged**
